FFT_2D:

  data:
    L: 1.0
    downsample_ratio: 4
    n_train: 800
    n_test: 200

  model:
    layer_types: ['GalerkinConv_pca','GalerkinConv_pca','GalerkinConv_pca']  # GalerkinConv_fourier ， GalerkinConv_pca ， FourierConv2d ，Attention
    FNO_modes: [16,16,16]   # modes for FourierConv2d
    GkNN_modes: [33,33,33]  # modes for GkNN
    num_heads: [1,1,1]
    attention_types: ["galerkin","galerkin","galerkin"]
    fc_dim: 128
    in_dim: 3  #default
    out_dim: 1  #default
    pca_include_input: False
    pca_include_grid: False
    layers_dim: [128,128,128,128]     # len(layers_dim) == len(..modes)+1
    act: 'gelu'
    pad_ratio: 0.05


  train:
    device: 'cpu'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 400
    scheduler: 'MultiStepLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 2
    normalization_x: True
    normalization_y: True
    normalization_dim: []

