Darcy:


  data:
    L: 1.0
    downsample_ratio: 14
    n_train: 800
    n_test: 200 

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    layer_types_local: ['GPDconv','GPDconv','GPDconv','GPDconv']
    # layer_types_local: ['GraphGaussconv','GraphGaussconv','GraphGaussconv','GraphGaussconv']
    phy_dim: 2
    kernel_mode: 16
    Fourier_para: 'para/darcy/Fourier7_uniform.pt'
    Gauss_para: 'para/darcy/baseweight_Gauss225_fixedpts.pt'
    # Morlet_para: 'para/advection/Morlet_pts10_freq61_uniform.pt'
    local_bases_type: 'Gauss'
    init_weight_GraphGaussconv: 500
    k: 121
    same_edge: False
    train_local_out: False
    train_local_weight: False
    fc_dim: 128
    in_dim: 3 
    out_dim: 1  #default
    layers_dim: [64,64,64,64,64]     # len(layers_dim) == len(..modes)+1 
    layer_hidden_dim: [8,8,8,8]
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 
    input_with_weight: True
    global_only: False
    local_only: True

  train:

    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 8
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0


  plot:
    plot_H_num: 0
    plot_hidden_layers_num: 4
    plot_bases_num: 0
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/darcy/test/
    save_figure_bases: figure/bases/
    plot_shape: [31,31]
    # plot_data_index: [0,6,11,23,24,25]



airfoil:

  data:
    L: 1.0
    downsample_ratio: 14
    n_train: 800
    n_test: 200 

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    layer_types_local: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']
    phy_dim: 1
    kernel_mode: 16
    Fourier_para: 'para/advection/Fourier65_uniform.pt'
    Gauss_para: 'para/advection/Gauss20_400_uniform.pt'
    Morlet_para: 'para/advection/Morlet_pts10_freq61_uniform.pt'
    local_bases_type: 'Gauss'
    train_local_out: False
    fc_dim: 128
    in_dim: 3 
    out_dim: 1  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 
    input_with_weight: True
    global_only: False
    local_only: False

  train:

    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 50
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0


  plot:
    plot_H_num: 0
    plot_hidden_layers_num: 6
    plot_bases_num: 0
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/advection/test/
    save_figure_bases: figure/bases/
    plot_shape: [31,31]
    plot_data_index: [0,6,11,23,24,25]


Advection:

  data:
    L: 1.0
    downsample_ratio: 1
    n_train: 1000
    n_test: 200 

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    layer_types_local: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']
    phy_dim: 1
    kernel_mode: 16
    Fourier_para: 'para/advection/Fourier65_uniform.pt'
    Gauss_para: 'para/advection/Gauss20_400_uniform.pt'
    Morlet_para: 'para/advection/Morlet_pts10_freq61_uniform.pt'
    local_bases_type: 'Morlet'
    train_local_out: False
    fc_dim: 128
    in_dim: 3 
    out_dim: 1  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 
    input_with_weight: True
    global_only: False
    local_only: False

  train:

    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 50
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0


  plot:
    plot_H_num: 0
    plot_hidden_layers_num: 6
    plot_bases_num: 0
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/advection/test/
    save_figure_bases: figure/bases/
    plot_shape: [31,31]
    plot_data_index: [0,6,11,23,24,25]