import torch
import torch.nn as nn

from .mpcno import (
    MPCNO,
    _get_act,
    compute_Fourier_modes,
    compute_Fourier_bases,
    compute_gradient,
    scaled_sigmoid,
)
from .mpcno_beta import MPCNO_train_multidist_beta


class DoubleLayerHyperSpectralConv(nn.Module):
    """
    Beta-conditioned spectral convolution where the effective weight is:

        W(beta) = W_base + W1 * sigma(W2 * beta + b)

    The hyper network output is split into three tensors (cos/sin/constant)
    and reshaped to the spectral weight shapes.
    """

    def __init__(self, in_channels, out_channels, modes, beta_dim, hyper_hidden=64, act="gelu"):
        super(DoubleLayerHyperSpectralConv, self).__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        nmodes, _, nmeasures = modes.shape
        self.nmodes = nmodes
        self.nmeasures = nmeasures
        self.scale = 1 / (in_channels * out_channels)

        # Base (beta-independent) spectral weights
        self.weights_c = nn.Parameter(
            self.scale * torch.rand(in_channels, out_channels, nmodes, nmeasures, dtype=torch.float)
        )
        self.weights_s = nn.Parameter(
            self.scale * torch.rand(in_channels, out_channels, nmodes, nmeasures, dtype=torch.float)
        )
        self.weights_0 = nn.Parameter(
            self.scale * torch.rand(in_channels, out_channels, 1, nmeasures, dtype=torch.float)
        )

        # Two-layer MLP: W1 sigma(W2 beta + b)
        self.hyper_act = _get_act(act)
        if self.hyper_act is None:
            raise ValueError("Hyper-network activation cannot be 'none'")

        c_size = in_channels * out_channels * nmodes * nmeasures
        s_size = in_channels * out_channels * nmodes * nmeasures
        z_size = in_channels * out_channels * 1 * nmeasures
        self._split_sizes = (c_size, s_size, z_size)

        self.hyper_w2 = nn.Linear(beta_dim, hyper_hidden)
        self.hyper_w1 = nn.Linear(hyper_hidden, c_size + s_size + z_size)

        # Start from base MPCNO behavior: delta W(beta) = 0 at init
        nn.init.zeros_(self.hyper_w1.weight)
        nn.init.zeros_(self.hyper_w1.bias)

    def forward(self, x, beta, bases_c, bases_s, bases_0, wbases_c, wbases_s, wbases_0):
        """
        x:      float [B, in_channels, N]
        beta:   float [B, beta_dim]
        return: float [B, out_channels, N]
        """
        B = x.shape[0]
        ic = self.in_channels
        oc = self.out_channels
        km = self.nmodes
        w = self.nmeasures

        hidden = self.hyper_act(self.hyper_w2(beta))
        delta_all = self.hyper_w1(hidden)
        dW_c_flat, dW_s_flat, dW_0_flat = torch.split(delta_all, self._split_sizes, dim=1)

        dW_c = dW_c_flat.view(B, ic, oc, km, w)
        dW_s = dW_s_flat.view(B, ic, oc, km, w)
        dW_0 = dW_0_flat.view(B, ic, oc, 1, w)

        weights_c = self.weights_c.unsqueeze(0) + dW_c
        weights_s = self.weights_s.unsqueeze(0) + dW_s
        weights_0 = self.weights_0.unsqueeze(0) + dW_0

        x_c_hat = torch.einsum("bix,bxkw->bikw", x, wbases_c)
        x_s_hat = -torch.einsum("bix,bxkw->bikw", x, wbases_s)
        x_0_hat = torch.einsum("bix,bxkw->bikw", x, wbases_0)

        f_c_hat = (
            torch.einsum("bikw,biokw->bokw", x_c_hat, weights_c)
            - torch.einsum("bikw,biokw->bokw", x_s_hat, weights_s)
        )
        f_s_hat = (
            torch.einsum("bikw,biokw->bokw", x_s_hat, weights_c)
            + torch.einsum("bikw,biokw->bokw", x_c_hat, weights_s)
        )
        f_0_hat = torch.einsum("bikw,biokw->bokw", x_0_hat, weights_0)

        return (
            torch.einsum("bokw,bxkw->box", f_0_hat, bases_0)
            + 2 * torch.einsum("bokw,bxkw->box", f_c_hat, bases_c)
            - 2 * torch.einsum("bokw,bxkw->box", f_s_hat, bases_s)
        )


class MPCNO_Beta(MPCNO):
    """
    Beta-conditioned MPCNO where the spectral kernels are generated by
    a two-layer hyper-network:

        W(beta) = W_base + W1 sigma(W2 beta + b)
    """

    def __init__(
        self,
        ndims,
        modes,
        nmeasures,
        layers,
        beta_dim,
        hyper_hidden=64,
        hyper_act="gelu",
        layer_selection={"grad": True, "geo": True, "geointegral": True},
        fc_dim=128,
        in_dim=3,
        out_dim=1,
        inv_L_scale_hyper=["independently", 0.5, 2.0],
        scaling_mode="inv",
        act="gelu",
        geo_act="softsign",
    ):
        super(MPCNO_Beta, self).__init__(
            ndims=ndims,
            modes=modes,
            nmeasures=nmeasures,
            layers=layers,
            layer_selection=layer_selection,
            fc_dim=fc_dim,
            in_dim=in_dim,
            out_dim=out_dim,
            inv_L_scale_hyper=inv_L_scale_hyper,
            scaling_mode=scaling_mode,
            act=act,
            geo_act=geo_act,
        )

        self.beta_dim = beta_dim

        self.sp_convs = nn.ModuleList(
            [
                DoubleLayerHyperSpectralConv(
                    in_size,
                    out_size,
                    modes,
                    beta_dim=beta_dim,
                    hyper_hidden=hyper_hidden,
                    act=hyper_act,
                )
                for in_size, out_size in zip(layers, layers[1:])
            ]
        )

        # Rebuild parameter groups because sp_convs changed
        self.normal_params = []
        self.inv_L_scale_params = []
        for _, param in self.named_parameters():
            if param is not self.inv_L_scale_latent:
                self.normal_params.append(param)
            else:
                if self.train_inv_L_scale == "together":
                    self.normal_params.append(param)
                elif self.train_inv_L_scale == "independently":
                    self.inv_L_scale_params.append(param)

    def forward(self, x, beta, aux):
        length = len(self.ws)

        node_mask, nodes, node_weights, directed_edges, edge_gradient_weights, outward_normals = aux

        bases_c, bases_s, bases_0 = compute_Fourier_bases(
            nodes,
            self.modes
            * scaled_sigmoid(
                self.inv_L_scale_latent, self.inv_L_scale_min, self.inv_L_scale_max
            ),
        )
        wbases_c = torch.einsum("bxkw,bxw->bxkw", bases_c, node_weights)
        wbases_s = torch.einsum("bxkw,bxw->bxkw", bases_s, node_weights)
        wbases_0 = torch.einsum("bxkw,bxw->bxkw", bases_0, node_weights)

        geo = (
            torch.cat(
                [
                    outward_normals,
                    compute_gradient(outward_normals, directed_edges, edge_gradient_weights),
                ],
                dim=1,
            )
            if self.layer_selection["geo"]
            else None
        )

        x = self.fc0(x)
        x = x.permute(0, 2, 1)

        for i, (speconv, spw, spconvnw, spconvadjnw, w, grad_layer, geo_emb) in enumerate(
            zip(
                self.sp_convs,
                self.sp_ws,
                self.sp_convs_nws,
                self.sp_convs_adj_nws,
                self.ws,
                self.grad_layers,
                self.geo_embs,
            )
        ):
            if self.layer_selection["geointegral"]:
                x_in = spconvnw(
                    torch.cat(
                        [x]
                        + [
                            x * outward_normals[:, j : j + 1, :]
                            for j in range(outward_normals.size(1))
                        ],
                        dim=1,
                    )
                )
                x1 = speconv(x_in, beta, bases_c, bases_s, bases_0, wbases_c, wbases_s, wbases_0)
                x1 = spw(x1) + spconvadjnw(
                    torch.cat(
                        [
                            x1 * outward_normals[:, j : j + 1, :]
                            for j in range(outward_normals.size(1))
                        ],
                        dim=1,
                    )
                )
            else:
                x1 = speconv(x, beta, bases_c, bases_s, bases_0, wbases_c, wbases_s, wbases_0)
                x1 = spw(x1)

            x2 = w(x)

            if self.layer_selection["grad"]:
                x_grad = grad_layer(x, directed_edges, edge_gradient_weights)
            else:
                x_grad = 0

            if self.layer_selection["geo"]:
                x_geo = geo_emb(geo, x)
            else:
                x_geo = 0

            if self.act is not None and i != length - 1:
                x = x + self.act(self.scale_factor * (x1 + x2 + x_grad + x_geo))
            else:
                x = self.scale_factor * (x1 + x2 + x_grad + x_geo)

        x = x.permute(0, 2, 1)

        if self.fc_dim > 0:
            x = self.fc1(x)
            if self.act is not None:
                x = self.act(x)

        x = self.fc2(x)
        return x
