Darcy_HGkNN:

  data:
    L: 1.0
    downsample_ratio: 14
    n_train: 800
    n_test: 200   #n_train + n_test < 1300

  model:
    # layer_types: ['lowrankHGalerkinConv','lowrankHGalerkinConv','lowrankHGalerkinConv','lowrankHGalerkinConv']
    layer_types: ['HGalerkinConv','HGalerkinConv','HGalerkinConv','HGalerkinConv']
    phy_dim: 2
    range_pts: [[0,1],[0,1]]
    pts_type: 'fixed'  #trained or fixed
    phybases_out: 'phy'  # phy or pca
    baseweight_type: 'same'  #same or parameter
    num_liftpts: 0
    num_basepts: 225  #must be a square
    liftradius: 200
    baseradius: 200
    minweight: 200
    fc_dim: 128
    in_dim: 3  #default
    out_dim: 1  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    # dropout: [0.1,0.1,0.1,0.1]
    dropout: [False,False,False,False]
    layer:
      GkNN_mode_in: 225  # modes for GkNN  ==num_basepts
      GkNN_mode_out_phybases: 128  # modes for GkNN
      kernel_mode: 48
      dim: 128
      rank: 20
      mask_mode: False



  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 8
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0
    update_base_ep: 0
    L1regularization_lambda_H1: 0.00001

  plot:
    plot_H_num: 0
    plot_hidden_layers: False
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/hidden_test/
    plot_shape: [31,31]