Darcy:

  data:
    L: 1.0
    downsample_ratio: 14
    n_train: 800
    n_test: 200   #n_train + n_test < 1300

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    layer_types_local: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']
    # layer_types_local: ['HGalerkinConv','HGalerkinConv','HGalerkinConv','HGalerkinConv']
    phy_dim: 2
    kernel_mode: 16
    Fourier_para: 'para/darcy/uniform_Fourier_225.pt'
    Gauss_para: 'para/darcy/baseweight_Gauss225_fixedpts.pt'
    train_local_pts: False
    train_local_weight: False
    fc_dim: 128
    in_dim: 3  #default
    out_dim: 1  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 
    input_with_weight: False
    with_local: True
    with_global: False

  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 8
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0


  plot:
    plot_H_num: 0
    plot_hidden_layers: False
    plot_bases_num: 0
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/hidden_test/
    save_figure_bases: figure/bases/
    plot_shape: [31,31]



car_normal:


  data:
    L: 1.0
    downsample_ratio: 1
    n_train: 500
    n_test: 100

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    layer_types_local: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']
    # layer_types_local: ['DGalerkinConv_local','DGalerkinConv_local','DGalerkinConv_local','DGalerkinConv_local']
    # layer_types_local: ['HGalerkinConv','HGalerkinConv','HGalerkinConv','HGalerkinConv']
    phy_dim: 3
    kernel_mode: 16
    Fourier_para: 'para/car/Fourier3_uniform.pt'
    Gauss_para: 'para/car/Gauss_343+100_100.pt'
    train_local_pts: True
    train_local_weight: True
    fc_dim: 128
    in_dim: 3 
    out_dim: 3  #default
    layers_dim: [64,64,64,64,64]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 
    input_with_weight: True
    with_local: True
    with_global: True

  train:

    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    basepts_lr_ratio: 100
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 10
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0
    # H_L1_reg: 0.001
    # pts_reg: 0.001

  plot:
    plot_H_num: 0
    plot_hidden_layers_num: False
    plot_bases_num: 1
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/car_normal/test_local_PhyHGkNN0/
    save_figure_bases: figure/bases_opt/
    plot_shape: [31,31]
    # plot_data_index: [0,6,11,23,24,25]


car_pressure:

  data:
    L: 1.0
    downsample_ratio: 1
    n_train: 500
    n_test: 100

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    # layer_types_local: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']
    # layer_types_local: ['DGalerkinConv_local','DGalerkinConv_local','DGalerkinConv_local','DGalerkinConv_local']
    layer_types_local: ['HGalerkinConv','HGalerkinConv','HGalerkinConv','HGalerkinConv']
    phy_dim: 3
    kernel_mode: 16
    Fourier_para: 'para/car/Fourier3_uniform.pt'
    Gauss_para: 'para/car/Gauss_343+100_100.pt'
    train_local_pts: True
    train_local_weight: True
    fc_dim: 128
    in_dim: 3 
    out_dim: 1  #default
    layers_dim: [64,64,64,64,64]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 
    input_with_weight: True
    with_local: True
    with_global: True

  train:

    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    basepts_lr_ratio: 100
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 10
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0
    # H_L1_reg: 0.001
    # pts_reg: 0.001

  plot:
    plot_H_num: 0
    plot_hidden_layers_num: 3
    plot_bases_num: 0
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/car_pressure/test1/
    save_figure_bases: figure/bases_press/
    plot_shape: [31,31]
    # plot_data_index: [0,6,11,23,24,25]