FFT_2D:

  data:
    L: 1.0
    downsample_ratio: 14
    n_train: 800
    n_test: 200

  model:
    # layer_types: ['DGalerkinConv_fourier','DGalerkinConv_fourier','DGalerkinConv_fourier','DGalerkinConv_fourier']  # DGalerkinConv_fourier ， DGalerkinConv_pca ， DGalerkinConv_doublepca
    # layer_types: ['DGalerkinConv_pca','DGalerkinConv_pca','DGalerkinConv_pca','DGalerkinConv_pca']
    layer_types: ['DGalerkinConv_doublepca','DGalerkinConv_doublepca','DGalerkinConv_doublepca','DGalerkinConv_doublepca']
    FNO_modes: [16,16,16,16]   # modes for FourierConv2d
    GkNN_modes: [96,96,96,96]  # modes for GkNN
    kernel_modes: [64,64,64,64]
    fc_dim: 128
    in_dim: 3  #default
    out_dim: 1  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    D_type : 'different'     #'same' or 'different'
    # dropout: [0.1,0.1,0.1,0.1]
    dropout: [False,False,False,False]



  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 8
    normalization_x: True
    normalization_y: True
    normalization_dim: []

