test:

  data:
    L: 1.0
    downsample_ratio: 14
    n_train: 800
    n_test: 200

  model:
    layer_types: ['HGalerkinConv','HGalerkinConv','HGalerkinConv','HGalerkinConv']  # HGalerkinConv,GalerkinConv
    coeff_compute: 'interpolation'  #dot_product or interpolation
    double_bases: False
    FNO_mode: [16,16,16,16]   # modes for FourierConv2d
    GkNN_mode: 96  # modes for GkNN
    kernel_mode: 64
    num_heads: [1,1,1,1]
    attention_types: ["galerkin","galerkin","galerkin","galerkin"]
    fc_dim: 128
    in_dim: 3  #default
    out_dim: 1  #default
    pca_include_input: False
    pca_include_grid: False
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    dropout: [False,False,False,False]





  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 8
    normalization_x: True
    normalization_y: True
    normalization_dim: []
    # L1regularization_lambda: 0.0001
    # hard_pruning: 0.0001
    # grad_clip: 1
    # L2regularization_alpha: 0.0005
    # L2regularization_beta: 0.001
    

