car_normal:


  data:
    L: 1.0
    downsample_ratio: 1
    n_train: 500
    n_test: 100

  model:
    layer_types_global: ['DGalerkinConv','DGalerkinConv','DGalerkinConv','DGalerkinConv']    
    # layer_types_local: ['GPDconv','GPDconv','GPDconv','GPDconv']
    layer_types_local: ['GraphGaussconv','GraphGaussconv','GraphGaussconv','GraphGaussconv']
    phy_dim: 3
    kernel_mode: 16
    Fourier_para: 'para/car/Fourier3_uniform.pt'
    Gauss_para: 'para/car/Gauss_loadpts343_100_off_boundary.pt'
    # Morlet_para: 'para/advection/Morlet_pts10_freq61_uniform.pt'
    local_bases_type: 'Gauss'
    init_weight_GraphGaussconv: 100
    k: 9
    same_edge: False
    train_local_out: False
    train_local_weight: False
    fc_dim: 128
    in_dim: 3  
    out_dim: 3  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    layer_hidden_dim: [32,32,32,32]
    act: 'gelu'
    dropout: [False,False,False,False]
    device: 'cuda' 

    input_with_weight: True
    global_only: True
    local_only: False

  train:

    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 20
    normalization_x: False
    normalization_y: True
    normalization_dim: []
    regularization_ep: 0


  plot:
    plot_H_num: 0
    plot_hidden_layers_num: 0
    plot_bases_num: 0
    save_figure_H: figure/H/bsz30/
    save_figure_hidden: figure/car_normal/test/
    save_figure_bases: figure/bases/
    plot_shape: [31,31]
    # plot_data_index: [0,6,11,23,24,25]

