airfoil_Galerkin:

  data:
    L: 1.0
    downsample_ratio: 1
    n_train: 1000
    n_test: 200

  model:
    layer_types: ['GalerkinConv_pca','GalerkinConv_pca','GalerkinConv_pca','GalerkinConv_pca']  # GalerkinConv_fourier ， GalerkinConv_pca ， FourierConv2d ，Attention
    # layer_types: ['FourierConv2d','FourierConv2d','FourierConv2d','FourierConv2d']  # GalerkinConv_fourier ， GalerkinConv_pca ， FourierConv2d ，Attention
    FNO_modes: [16,16,16,16]   # modes for FourierConv2d
    GkNN_modes: [512,512,512,512]  # modes for GkNN
    num_heads: [1,1,1,1]
    attention_types: ["galerkin","galerkin","galerkin","galerkin"]
    fc_dim: 128
    in_dim: 4  #default
    out_dim: 1  #default
    pca_include_input: False
    pca_include_grid: False
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    pad_ratio: 0.05
    residual : [False,False,False,False]


  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 10
    normalization_x: True
    normalization_y: True
    normalization_dim: []




airfoil_HGkNN:

  data:
    L: 1.0
    downsample_ratio: 1
    n_train: 300
    n_test: 200

  model:
    layer_types: ['HGalerkinConv','HGalerkinConv','HGalerkinConv','HGalerkinConv']
    double_bases: False
    GkNN_mode: 96  # modes for GkNN
    kernel_mode: 64
    fc_dim: 128
    in_dim: 4  #default
    out_dim: 1  #default
    layers_dim: [128,128,128,128,128]     # len(layers_dim) == len(..modes)+1 
    act: 'gelu'
    # dropout: [0.1,0.1,0.1,0.1]
    dropout: [False,False,False,False]



  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 500
    scheduler: 'OneCycleLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 30
    normalization_x: True
    normalization_y: True
    normalization_dim: []
    # L1regularization_lambda: 0.0001
    # hard_pruning: 0.0001
    # grad_clip: 1
    # L2regularization_alpha: 0.0005
    # L2regularization_beta: 0.001
