###########################################################################
# config for darcy 2d
###########################################################################
darcy2d:
  data:
    type: "graph"
    neighbor_size: 7
    L: 1.0
    downsample_ratio: 2
    n_train: 1000
    n_test: 200
    pca_include_input: False
    pca_include_grid: False
    should_include_grid: False
    should_include_F: False
    should_flatten: True
    should_compute_bases: False

  model:
    # Network Construction
    in_dim: 3
    out_dim: 1
    fc_channels: 128
    layer_channels: [128, 128, 128, 128, 128]
    act: "gelu"

  train:
    device: "cuda"

    normalization_x: True
    normalization_y: True
    normalization_dim: []

    epochs: 500
    batch_size: 8

    scheduler: "OneCycleLR"
    base_lr: 0.001
    weight_decay: 0.0001

    # MultiStep
    milestones:
    scheduler_gamma:

###########################################################################
# config for airfoil
###########################################################################
airfoil:
  data:
    type: "graph"
    neighbor_size: 5
    L: 1.0
    downsample_ratio: 2
    n_train: 1000
    n_test: 200
    pca_include_input: False
    pca_include_grid: False
    should_include_grid: False
    should_include_F: False
    should_flatten: True
    should_compute_bases: False

  model:
    # Network Construction
    in_dim: 4
    out_dim: 1
    fc_channels: 128
    layer_channels: [64, 64, 64, 64, 64]
    act: "gelu"

  train:
    device: "cuda"

    normalization_x: True
    normalization_y: True
    normalization_dim: []

    epochs: 500
    batch_size: 30

    scheduler: "OneCycleLR"
    base_lr: 0.001
    weight_decay: 0.0001

    # MultiStep
    milestones:
    scheduler_gamma:
