FFT_1D:

  data:
    L: 1.0
    downsample_ratio: 16
    n_train: 1024
    n_test: 1024

  model:
    basis_type: 'Galerkin_bases'  #Fast_Fourier_Transform , Fourier_bases , Galerkin_bases
    FNO_modes: [16,16,16]   # modes for FNO
    GkNN_modes: [33,33,33]  # modes for GkNN
    fc_dim: 128
    in_dim: 2  #default
    out_dim: 1  #default
    pca_include_input: False
    pca_include_grid: False
    layers: [128,128,128,128]     # len(layers) == len(..modes)+1
    act: 'gelu'
    pad_ratio: 0.05


  train:
    device: 'cuda'   #cpu or cuda
    base_lr: 0.001
    weight_decay: 0.0001
    epochs: 1000
    scheduler: 'MultiStepLR'
    milestones: [200,300,400,500,800,900]
    scheduler_gamma: 0.5
    batch_size: 64
    normalization_x: True
    normalization_y: True
    normalization_dim: []

